baseURL = 'https://blogs.masihur.dev/'
languageCode = 'en-us'
title = "Masihur's Blog"
theme = "paper"

[taxonomies]
   tag = "tags"
   category = "categories"

[params]
  # color style
  color = 'linen'                 # linen, wheat, gray, light

  # header social icons
  twitter = 'YOUR_TWITTER_ID'     # twitter.com/YOUR_TWITTER_ID
  github = 'YOUR_GITHUB_ID'       # github.com/YOUR_GITHUB_ID
  linkedin = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                      # show rss icon with link

  # home page profile
  avatar = 'https://deno.land/logo.svg'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  name = 'Masihur R. Maruf'
  bio = 'Working as a Senior Software Engineer. Everyday dealing with programming language like nidejs, python, go. Love to get challenges and solve them.'

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = true             # show monochrome dark mode icon
